"""initial schema

Revision ID: 1ea65edbac8d
Revises: 
Create Date: 2026-06-28 03:11:30.278934

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1ea65edbac8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_headers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tokenusagedaily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'provider_id', 'model', 'request_kind')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('supports_tools', sa.Boolean(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('role_default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_provider_id'), ['provider_id'], unique=False)

    op.create_table('tokenusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('request_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokenusage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenusage_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusage_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusage_request_kind'), ['request_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenusage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenusage_request_kind'))
        batch_op.drop_index(batch_op.f('ix_tokenusage_provider_id'))
        batch_op.drop_index(batch_op.f('ix_tokenusage_model'))
        batch_op.drop_index(batch_op.f('ix_tokenusage_day'))

    op.drop_table('tokenusage')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_provider_id'))
        batch_op.drop_index(batch_op.f('ix_model_model_id'))

    op.drop_table('model')
    op.drop_table('tokenusagedaily')
    op.drop_table('setting')
    op.drop_table('provider')
    # ### end Alembic commands ###
