"""concept paperconcept

Revision ID: 5bb18f2ea5f6
Revises: 82deac2cc72e
Create Date: 2026-06-28 12:19:30.078158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5bb18f2ea5f6'
down_revision = '82deac2cc72e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_concept_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_normalized_key'), ['normalized_key'], unique=True)

    op.create_table('paperconcept',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysisrun.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paperconcept')
    with op.batch_alter_table('concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_normalized_key'))

    op.drop_table('concept')
    # ### end Alembic commands ###
