"""paper analysis summary

Revision ID: 82deac2cc72e
Revises: 1ea65edbac8d
Create Date: 2026-06-28 12:09:38.599443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '82deac2cc72e'
down_revision = '1ea65edbac8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authors_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arxiv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('title_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_arxiv_id'), ['arxiv_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_title_norm'), ['title_norm'], unique=False)

    op.create_table('analysisrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysisrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysisrun_paper_id'), ['paper_id'], unique=False)

    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('content_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysisrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_paper_id'), ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_paper_id'))

    op.drop_table('summary')
    with op.batch_alter_table('analysisrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysisrun_paper_id'))

    op.drop_table('analysisrun')
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_title_norm'))
        batch_op.drop_index(batch_op.f('ix_paper_doi'))
        batch_op.drop_index(batch_op.f('ix_paper_arxiv_id'))

    op.drop_table('paper')
    # ### end Alembic commands ###
